
project_id = "gowdckitwgmctqlpqzod"

[functions.create-demo-user]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.send-push]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
