project_id = "wwgljhpuulhljumrhscg"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.get-turnstile-config]
    verify_jwt = false
  [functions.google-ads-oauth-callback]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.verify-turnstile]
    verify_jwt = false
