// Auto-generates public/sitemap.xml from the canonical route list + dynamic data.
// Runs on predev and prebuild so every deploy ships an up-to-date sitemap.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  STATIC_SITEMAP_ENTRIES,
  type SitemapEntry,
} from "../src/data/sitemapEntries";
import { redirectForPath } from "../src/lib/seoRouting";

const BASE_URL = "https://maintenease.com";
const SUPABASE_URL = "https://wwgljhpuulhljumrhscg.supabase.co";
const SUPABASE_ANON =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Z2xqaHB1dWxobGp1bXJoc2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMTgzOTAsImV4cCI6MjA5NDY5NDM5MH0.21tgSpPihdVl5XE9pFpwFzvaD2I05DE7uGzkuI7u6ac";

async function fetchBlogEntries(): Promise<SitemapEntry[]> {
  try {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/blog_posts?select=slug,updated_at,published_at&order=published_at.desc.nullslast&limit=5000`,
      { headers: { apikey: SUPABASE_ANON, Authorization: `Bearer ${SUPABASE_ANON}` } },
    );
    if (!res.ok) {
      console.warn(`[sitemap] blog fetch failed: ${res.status}`);
      return [];
    }
    const rows = (await res.json()) as Array<{
      slug: string;
      updated_at: string | null;
      published_at: string | null;
    }>;
    return rows
      .map((r) => ({
        path: `/blog/${r.slug}`,
        lastmod: (r.updated_at ?? r.published_at ?? "").slice(0, 10) || undefined,
        changefreq: "weekly" as const,
        priority: "0.7",
      }))
      .filter((entry) => !redirectForPath(entry.path));
  } catch (err) {
    console.warn(`[sitemap] blog fetch error: ${(err as Error).message}`);
    return [];
  }
}

const blogEntries = await fetchBlogEntries();
const latestBlogLastmod = blogEntries
  .map((entry) => entry.lastmod)
  .filter((lastmod): lastmod is string => Boolean(lastmod))
  .sort()
  .at(-1);
const entries = [
  ...STATIC_SITEMAP_ENTRIES.map((entry) =>
    entry.path === "/blog" ? { ...entry, lastmod: latestBlogLastmod } : entry,
  ),
  ...blogEntries,
];

function render(entries: SitemapEntry[]): string {
  const urls = entries.map((e) =>
    [
      "  <url>",
      `    <loc>${BASE_URL}${e.path}</loc>`,
      e.lastmod ? `    <lastmod>${e.lastmod}</lastmod>` : null,
      e.changefreq ? `    <changefreq>${e.changefreq}</changefreq>` : null,
      e.priority ? `    <priority>${e.priority}</priority>` : null,
      "  </url>",
    ]
      .filter(Boolean)
      .join("\n"),
  );

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    "</urlset>",
    "",
  ].join("\n");
}

const outPath = resolve("public/sitemap.xml");
writeFileSync(outPath, render(entries));
console.log(`[sitemap] wrote ${entries.length} URLs → public/sitemap.xml`);

const routeManifestPath = resolve("src/data/generatedIndexableRoutes.ts");
const generatedRoutes = [...new Set(entries.map((entry) => entry.path))].sort();
writeFileSync(
  routeManifestPath,
  [
    "// Generated by scripts/generate-sitemap.ts. Commit this file so edge builds",
    "// never fall back to accepting every syntactically valid content slug.",
    "export const GENERATED_INDEXABLE_ROUTES = [",
    ...generatedRoutes.map((path) => `  ${JSON.stringify(path)},`),
    "] as const;",
    "",
  ].join("\n"),
);
console.log(`[sitemap] wrote ${generatedRoutes.length} known routes → src/data/generatedIndexableRoutes.ts`);
