// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-work-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_work_orders_default = defineTool({
  name: "list_work_orders",
  title: "List work orders",
  description: "List work orders for the signed-in user's company. Optional status filter.",
  inputSchema: {
    status: z.enum(["pending", "in_progress", "completed", "cancelled"]).optional().describe("Filter by work order status."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client(ctx).from("work_orders").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-work-order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_work_order_default = defineTool2({
  name: "create_work_order",
  title: "Create work order",
  description: "Create a new maintenance work order for the signed-in user's company.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Short title for the work order."),
    description: z2.string().optional().describe("Longer description of the work needed."),
    priority: z2.enum(["low", "medium", "high", "urgent"]).optional().describe("Priority. Defaults to medium."),
    due_date: z2.string().datetime().optional().describe("ISO 8601 due date."),
    asset_id: z2.string().uuid().optional().describe("Related asset id, if known.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, priority, due_date, asset_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client2(ctx);
    const { data: companyId, error: companyErr } = await sb.rpc("get_user_company", {
      _user_id: ctx.getUserId()
    });
    if (companyErr) return { content: [{ type: "text", text: companyErr.message }], isError: true };
    const { data, error } = await sb.from("work_orders").insert({
      title,
      description: description ?? null,
      priority: priority ?? "medium",
      status: "pending",
      due_date: due_date ?? null,
      asset_id: asset_id ?? null,
      created_by: ctx.getUserId(),
      company_id: companyId
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created work order ${data?.id}` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/list-assets.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.106.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_assets_default = defineTool3({
  name: "list_assets",
  title: "List assets",
  description: "List equipment/assets the signed-in user's company tracks.",
  inputSchema: {
    search: z3.string().optional().describe("Case-insensitive name search."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client3(ctx).from("assets").select("*").order("name").limit(limit ?? 50);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-locations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.106.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_locations_default = defineTool4({
  name: "list_locations",
  title: "List locations",
  description: "List buildings/sites/rooms the signed-in user's company tracks.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client4(ctx).from("locations").select("*").order("name").limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-requests.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.106.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_requests_default = defineTool5({
  name: "list_maintenance_requests",
  title: "List maintenance requests",
  description: "List incoming maintenance requests in the request inbox for the signed-in user's company.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client5(ctx).from("public_requests").select("*").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wwgljhpuulhljumrhscg";
var mcp_default = defineMcp({
  name: "maintenease-mcp",
  title: "MaintenEase",
  version: "0.1.0",
  instructions: "Tools for MaintenEase, a CMMS. Use these tools to list and create work orders, browse assets and locations, and read the maintenance request inbox for the signed-in user's company. All tools are tenant-scoped by RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_work_orders_default, create_work_order_default, list_assets_default, list_locations_default, list_requests_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
